apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: blackhole
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      protocol: TCP
