apiVersion: v1
kind: Service
metadata:
  name: ray-api
  labels:
    app: ray-api
    app.kubernetes.io/name: ray-api
    app.kubernetes.io/part-of: blackhole
spec:
  type: NodePort
  selector:
    app: ray-api
  ports:
    - port: {{ .Values.rayApi.port | default 8000 }}
      targetPort: {{ .Values.rayApi.port | default 8000 }}
      nodePort: {{ .Values.rayApi.nodePort | default 30081 }}
      protocol: TCP
