apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: blackhole
    tier: frontend
    system: blackhole
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: blackhole
        tier: frontend
        system: blackhole
    spec:
      containers:
        - name: ui
          image: marilee/blackhole-k8s:ui-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: ui-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: ui-index
          configMap:
            name: ui-index
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: blackhole
    tier: frontend
    system: blackhole
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/component: frontend
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
